gnodeb:
  controlif:
    ip: "NGAP_LOCAL_ADDR"
    port: 9487
  dataif:
    ip: "GTPU_LOCAL_ADDR"
    port: 2152
  plmnlist:
    mcc: "MCC"
    mnc: "MNC"
    tac: "TAC"
    gnbid: "GNBID"
  slicesupportlist:
    sst: "SST_GNB"
    sd: "000001"
  test: "test-normal-registration"
ue:
  msin: "MSIN"
  key: "KEY"
  opc: "OPC"
  amf: "8000"
  sqn: "0000000"
  dnn: "DNN"
  hplmn:
    mcc: "MCC"
    mnc: "MNC"
  snssai:
    sst: "SST_UE"
    sd: "000001"
  integrity:
    nia0: false
    nia1: false
    nia2: true
  ciphering:
    nea0: true
    nea1: false
    nea2: false
  test: "test-5g-guti"
amfif:
  ip: "NGAP_REMOTE_ADDR"
  port: 38412
logs:
    level: 4
